package view;

import java.awt.Component;
import java.awt.Container;
import java.math.BigInteger;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import lib.Utils;
import model.Item;
import model.Unit;
import service.ItemService;
import service.UnitService;

/**
 *
 * @author LENOVO
 */
public class ItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form Form_Item
     */
    private ItemService service = new ItemService();
    private UnitService unitService = new UnitService();
    private int SelectedID;

    public ItemPanel() {
        initComponents();
        loadData(null);
        loadComboBoxUnit();
    }

    private void loadData(String query) {
        DefaultTableModel model = (DefaultTableModel) datatable.getModel();
        model.setRowCount(0);

        List<Item> items = service.getItems(query);

        for (Item item : items) {
            Object[] row = {
                item.getId(),
                item.getName(),
                Utils.formatNumberToRupiah(item.getPrice()),
                Utils.formatNumberWithDotSeparator(item.getQuantity()),
                item.getMin_quantity(),
                item.getUnitName()
            };

            model.addRow(row);
        }
    }

    private void loadComboBoxUnit() {
        List<Unit> units = unitService.getUnits();
        DefaultComboBoxModel<String> modelUnit = new DefaultComboBoxModel<>();
        modelUnit.addElement("-- Pilih Unit --");

        for (Unit unit : units) {
            modelUnit.addElement(unit.getName());
        }
        input_unit.setModel(modelUnit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        data_item = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datatable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bt_tambahdata = new javax.swing.JButton();
        t_cari = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bt_hapus = new javax.swing.JButton();
        bt_edit = new javax.swing.JButton();
        tambah_item = new javax.swing.JPanel();
        add_edit_label = new javax.swing.JLabel();
        form_tambah_item = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        input_name = new javax.swing.JTextField();
        input_harga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        input_kuantitas = new javax.swing.JTextField();
        bt_simpan = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        input_unit = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        input_minimum_kuantitas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        main_panel.setLayout(new java.awt.CardLayout());

        data_item.setBackground(new java.awt.Color(255, 255, 255));

        datatable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        datatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Item", "Harga", "Kuantitas", "Minimum", "Unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(datatable);
        if (datatable.getColumnModel().getColumnCount() > 0) {
            datatable.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Data Item");

        bt_tambahdata.setBackground(new java.awt.Color(26, 70, 136));
        bt_tambahdata.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bt_tambahdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata.setText("Tambah");
        bt_tambahdata.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdataActionPerformed(evt);
            }
        });

        t_cari.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        t_cari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_cari.setText("Pencarian");
        t_cari.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cariActionPerformed(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_cariKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Hello, {nama}");

        bt_hapus.setBackground(new java.awt.Color(26, 70, 136));
        bt_hapus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bt_hapus.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapus.setText("Hapus");
        bt_hapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        bt_edit.setBackground(new java.awt.Color(26, 70, 136));
        bt_edit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bt_edit.setForeground(new java.awt.Color(255, 255, 255));
        bt_edit.setText("Edit");
        bt_edit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout data_itemLayout = new javax.swing.GroupLayout(data_item);
        data_item.setLayout(data_itemLayout);
        data_itemLayout.setHorizontalGroup(
            data_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_itemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                    .addGroup(data_itemLayout.createSequentialGroup()
                        .addGroup(data_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(data_itemLayout.createSequentialGroup()
                                .addComponent(bt_tambahdata)
                                .addGap(18, 18, 18)
                                .addComponent(bt_edit)
                                .addGap(23, 23, 23)
                                .addComponent(bt_hapus)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(data_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t_cari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        data_itemLayout.setVerticalGroup(
            data_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_itemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(data_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(bt_tambahdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );

        main_panel.add(data_item, "card2");

        tambah_item.setBackground(new java.awt.Color(255, 255, 255));

        add_edit_label.setBackground(new java.awt.Color(255, 255, 255));
        add_edit_label.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        add_edit_label.setText("Tambah Item");

        form_tambah_item.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nama");

        input_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        input_name.setText("  ");
        input_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        input_harga.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        input_harga.setText("  ");
        input_harga.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Harga");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Kuantitas");

        input_kuantitas.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        input_kuantitas.setText("  ");
        input_kuantitas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        input_kuantitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_kuantitasActionPerformed(evt);
            }
        });

        bt_simpan.setBackground(new java.awt.Color(26, 70, 136));
        bt_simpan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_simpan.setForeground(new java.awt.Color(255, 255, 255));
        bt_simpan.setText("Simpan");
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });

        bt_batal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_batal.setText("Batal");
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Unit");

        input_unit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        input_unit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Unit -", "Pcs", "Pack", "Box", "Sak" }));
        input_unit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        input_unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_unitActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Kuantitas Minimum");

        input_minimum_kuantitas.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        input_minimum_kuantitas.setText("  ");
        input_minimum_kuantitas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        input_minimum_kuantitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_minimum_kuantitasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout form_tambah_itemLayout = new javax.swing.GroupLayout(form_tambah_item);
        form_tambah_item.setLayout(form_tambah_itemLayout);
        form_tambah_itemLayout.setHorizontalGroup(
            form_tambah_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, form_tambah_itemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(form_tambah_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(input_unit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input_name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_harga, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_kuantitas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, form_tambah_itemLayout.createSequentialGroup()
                        .addGroup(form_tambah_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(form_tambah_itemLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(input_minimum_kuantitas, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        form_tambah_itemLayout.setVerticalGroup(
            form_tambah_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_tambah_itemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_kuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_minimum_kuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(form_tambah_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Hello, {nama} ");

        javax.swing.GroupLayout tambah_itemLayout = new javax.swing.GroupLayout(tambah_item);
        tambah_item.setLayout(tambah_itemLayout);
        tambah_itemLayout.setHorizontalGroup(
            tambah_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambah_itemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambah_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(form_tambah_item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tambah_itemLayout.createSequentialGroup()
                        .addComponent(add_edit_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 507, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );
        tambah_itemLayout.setVerticalGroup(
            tambah_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambah_itemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambah_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_edit_label)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(form_tambah_item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        main_panel.add(tambah_item, "card2");

        add(main_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void input_kuantitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_kuantitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_kuantitasActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        main_panel.removeAll();
        main_panel.add(data_item);
        main_panel.repaint();
        main_panel.revalidate();

        add_edit_label.setText("Tambah Item");

        input_name.setText("");
        input_harga.setText("");
        input_kuantitas.setText("");
        input_minimum_kuantitas.setText("");
        input_unit.setSelectedIndex(0);
    }//GEN-LAST:event_bt_batalActionPerformed

    private void input_unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_unitActionPerformed

    private void bt_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdataActionPerformed
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();

        main_panel.add(tambah_item);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_bt_tambahdataActionPerformed

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_t_cariKeyTyped

    private void input_minimum_kuantitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_minimum_kuantitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_minimum_kuantitasActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = datatable.getSelectedRow();
        if (selectedRow != -1) {
            Object value = datatable.getValueAt(selectedRow, 0);

            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Yakin mau hapus data ini?",
                    "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                int id = Integer.parseInt(value.toString()); // atau cast kalau yakin Integer
                boolean success = service.deleteItem(id);
                if (success) {
                    loadData(null);

                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
                    // refresh table kalau perlu
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data dulu yang mau dihapus.");
        }
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void bt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editActionPerformed
        // TODO add your handling code here:
        int selectedRow = datatable.getSelectedRow();
        if (selectedRow != -1) {
            Object value = datatable.getValueAt(selectedRow, 0);

            main_panel.removeAll();
            main_panel.repaint();
            main_panel.revalidate();

            main_panel.add(tambah_item);
            main_panel.repaint();
            main_panel.revalidate();

            int id = (int) value;
            Item success = service.getItemById(id);

            /*
            1. Ganti title "Tambah Item" menjadi "Edit Item"
            add_edit_label.setText("Edit Item")
            2. Isi semua input dengan data yang dikembalikan dari service (Item)
            3. Ketika tekan tombol simpan maka simpan semua perubahan ke Database (service.update)
            4. Kosongkan kembali semua input dan text menjadi "Tambah Item"
             */
//            1. Ganti title "Tambah Item" menjadi "Edit Item"
            add_edit_label.setText("Edit Item");

//            2. Isi semua input dengan data yang dikembalikan dari service (Item)
            input_name.setText(success.getName());
            input_harga.setText(success.getPrice().toString());
            input_kuantitas.setText(String.valueOf(success.getQuantity()));
            input_minimum_kuantitas.setText(String.valueOf(success.getMin_quantity()));
            input_unit.setSelectedIndex(success.getUnit());
            bt_simpan.setText("Perbarui");

//            Passing SelectedID, untuk digunakan nanti di form edit
            this.SelectedID = id;
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data dulu yang mau dihapus.");
        }
    }//GEN-LAST:event_bt_editActionPerformed

    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
        // TODO add your handling code here
        //        Get Data from Form
        int id = this.SelectedID;
        String name = input_name.getText().trim();
        BigInteger price = new BigInteger(input_harga.getText().trim());
        int quantity = Integer.parseInt(input_kuantitas.getText().trim());
        int min_quantity = Integer.parseInt(input_minimum_kuantitas.getText().trim());
        int unit = input_unit.getSelectedIndex();

//        Create Object Item
//        Insert or Update Data
        boolean status;
        if (bt_simpan.getText().toLowerCase().equals("perbarui")) {
            Item item = new Item(id, name, price, quantity, min_quantity, unit);
            status = service.updateItem(item);

//            Reset text tombol menjadi simpan kembali
            bt_simpan.setText("Simpan");
        } else {
            Item item = new Item(name, price, quantity, min_quantity, unit);
            status = service.insertItem(item);
        }

        if (status) {
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
            clearForm(form_tambah_item); // optional: bersihkan form

//        Back to Table Item
            main_panel.removeAll();
            main_panel.add(data_item);
            main_panel.repaint();
            main_panel.revalidate();

//            Refresh Table
            loadData(null);
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data");
        }
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void t_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyReleased
        // TODO add your handling code here:
        String keyword = t_cari.getText().trim();
        loadData(keyword);
    }//GEN-LAST:event_t_cariKeyReleased

    private void t_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_cariActionPerformed
    private void clearForm(Component parent) {
        if (parent instanceof JTextField) {
            ((JTextField) parent).setText("");
        } else if (parent instanceof JComboBox) {
            ((JComboBox<?>) parent).setSelectedIndex(0);
        } else if (parent instanceof JSpinner) {
            ((JSpinner) parent).setValue(0);
        } else if (parent instanceof JCheckBox) {
            ((JCheckBox) parent).setSelected(false);
        } else if (parent instanceof JPanel || parent instanceof Container) {
            for (Component c : ((Container) parent).getComponents()) {
                clearForm(c);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_edit_label;
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_edit;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JButton bt_tambahdata;
    private javax.swing.JPanel data_item;
    private javax.swing.JTable datatable;
    private javax.swing.JPanel form_tambah_item;
    private javax.swing.JTextField input_harga;
    private javax.swing.JTextField input_kuantitas;
    private javax.swing.JTextField input_minimum_kuantitas;
    private javax.swing.JTextField input_name;
    private javax.swing.JComboBox<String> input_unit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField t_cari;
    private javax.swing.JPanel tambah_item;
    // End of variables declaration//GEN-END:variables
}
