/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Component;
import java.awt.Container;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import lib.Utils;
import model.Supplier;
import service.SupplierService;

/**
 *
 * @author LENOVO
 */
public class SupplierPanel extends javax.swing.JPanel {

    /**
     * Creates new form Form_Item
     */
    private final SupplierService supplierService = new SupplierService();
    private int SelectedID;

    public SupplierPanel() {
        initComponents();
        loadData(null);
    }

    private void loadData(String query) {
        DefaultTableModel model = (DefaultTableModel) datatable.getModel();
        model.setRowCount(0);

        List<Supplier> suppliers = supplierService.getSuppliers(query);

        for (Supplier supplier : suppliers) {
            Object[] row = {
                supplier.getId(),
                supplier.getName(),
                supplier.getPhone(),
                supplier.getAddress(),};

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        data_supplier = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datatable = new javax.swing.JTable();
        add_edit_label = new javax.swing.JLabel();
        bt_tambahdata = new javax.swing.JButton();
        t_cari = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bt_edit = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        tambah_supplier = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        form_tambah = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        input_name = new javax.swing.JTextField();
        input_phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        input_address = new javax.swing.JTextField();
        bt_simpan = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        main_panel.setLayout(new java.awt.CardLayout());

        data_supplier.setBackground(new java.awt.Color(255, 255, 255));

        datatable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        datatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama Supplier", "No. HP", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(datatable);
        if (datatable.getColumnModel().getColumnCount() > 0) {
            datatable.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        add_edit_label.setBackground(new java.awt.Color(255, 255, 255));
        add_edit_label.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        add_edit_label.setText("Data Supplier");

        bt_tambahdata.setBackground(new java.awt.Color(26, 70, 136));
        bt_tambahdata.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bt_tambahdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata.setText("Tambah");
        bt_tambahdata.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdataActionPerformed(evt);
            }
        });

        t_cari.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        t_cari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_cari.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cariActionPerformed(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_cariKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Hello, {nama}");

        bt_edit.setBackground(new java.awt.Color(26, 70, 136));
        bt_edit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bt_edit.setForeground(new java.awt.Color(255, 255, 255));
        bt_edit.setText("Edit");
        bt_edit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editActionPerformed(evt);
            }
        });

        bt_hapus.setBackground(new java.awt.Color(26, 70, 136));
        bt_hapus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bt_hapus.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapus.setText("Hapus");
        bt_hapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout data_supplierLayout = new javax.swing.GroupLayout(data_supplier);
        data_supplier.setLayout(data_supplierLayout);
        data_supplierLayout.setHorizontalGroup(
            data_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_supplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                    .addGroup(data_supplierLayout.createSequentialGroup()
                        .addGroup(data_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_edit_label, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(data_supplierLayout.createSequentialGroup()
                                .addComponent(bt_tambahdata)
                                .addGap(18, 18, 18)
                                .addComponent(bt_edit)
                                .addGap(18, 18, 18)
                                .addComponent(bt_hapus)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(data_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t_cari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        data_supplierLayout.setVerticalGroup(
            data_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_supplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_edit_label)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(data_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );

        main_panel.add(data_supplier, "card2");

        tambah_supplier.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Tambah Supplier");

        form_tambah.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nama");

        input_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        input_name.setText("  ");
        input_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        input_phone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        input_phone.setText("  ");
        input_phone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("No. HP");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Alamat");

        input_address.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        input_address.setText("  ");
        input_address.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        input_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_addressActionPerformed(evt);
            }
        });

        bt_simpan.setBackground(new java.awt.Color(26, 70, 136));
        bt_simpan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_simpan.setForeground(new java.awt.Color(255, 255, 255));
        bt_simpan.setText("Simpan");
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });

        bt_batal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_batal.setText("Batal");
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout form_tambahLayout = new javax.swing.GroupLayout(form_tambah);
        form_tambah.setLayout(form_tambahLayout);
        form_tambahLayout.setHorizontalGroup(
            form_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, form_tambahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(form_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(input_name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_phone, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_address, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, form_tambahLayout.createSequentialGroup()
                        .addGroup(form_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 675, Short.MAX_VALUE))
                    .addGroup(form_tambahLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        form_tambahLayout.setVerticalGroup(
            form_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_tambahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_address, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(form_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Hello, {nama} ");

        javax.swing.GroupLayout tambah_supplierLayout = new javax.swing.GroupLayout(tambah_supplier);
        tambah_supplier.setLayout(tambah_supplierLayout);
        tambah_supplierLayout.setHorizontalGroup(
            tambah_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambah_supplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambah_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(form_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tambah_supplierLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 470, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );
        tambah_supplierLayout.setVerticalGroup(
            tambah_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambah_supplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambah_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(form_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        main_panel.add(tambah_supplier, "card2");

        add(main_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void input_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_addressActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        main_panel.removeAll();
        main_panel.add(data_supplier);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_bt_batalActionPerformed

    private void bt_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdataActionPerformed
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();

        main_panel.add(tambah_supplier);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_bt_tambahdataActionPerformed

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked

    }//GEN-LAST:event_t_cariMouseClicked

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped

    }//GEN-LAST:event_t_cariKeyTyped

    private void bt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editActionPerformed
        // TODO add your handling code here:
        int selectedRow = datatable.getSelectedRow();
        if (selectedRow != -1) {
            Object value = datatable.getValueAt(selectedRow, 0);

            main_panel.removeAll();
            main_panel.repaint();
            main_panel.revalidate();

            main_panel.add(tambah_supplier);
            main_panel.repaint();
            main_panel.revalidate();

            int id = (int) value;
            Supplier success = supplierService.getSupplierById(id);

//            1. Ganti title "Tambah Item" menjadi "Edit Item"
            add_edit_label.setText("Edit Supplier");

//            2. Isi semua input dengan data yang dikembalikan dari service (Item)
            input_name.setText(success.getName());
            input_phone.setText(success.getPhone());
            input_address.setText(success.getAddress());
            bt_simpan.setText("Perbarui");

//            Passing SelectedID, untuk digunakan nanti di form edit
            this.SelectedID = id;
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data dulu yang mau dihapus.");
        }
    }//GEN-LAST:event_bt_editActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = datatable.getSelectedRow();
        if (selectedRow != -1) {
            Object value = datatable.getValueAt(selectedRow, 0);

            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Yakin mau hapus data ini?",
                    "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                int id = Integer.parseInt(value.toString()); // atau cast kalau yakin Integer
                boolean success = supplierService.deleteSupplier(id);
                if (success) {
                    loadData(null);

                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
                    // refresh table kalau perlu
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data dulu yang mau dihapus.");
        }
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
        // TODO add your handling code here:
        int id = this.SelectedID;
        String name = input_name.getText().trim();
        String phone = input_phone.getText().trim();
        String address = input_address.getText().trim();

        boolean status;
        if (bt_simpan.getText().toLowerCase().equals("perbarui")) {
            Supplier item = new Supplier(id, name, phone, address);
            status = supplierService.updateSupplier(item);

//            Reset text tombol menjadi simpan kembali
            bt_simpan.setText("Simpan");
        } else {
            Supplier item = new Supplier(name, phone, address);
            status = supplierService.insertSupplier(item);
        }

        if (status) {
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
            clearForm(form_tambah); // optional: bersihkan form

//        Back to Table Item
            main_panel.removeAll();
            main_panel.add(data_supplier);
            main_panel.repaint();
            main_panel.revalidate();

//            Refresh Table
            loadData(null);
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data");
        }
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void t_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_cariActionPerformed

    private void t_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyReleased
        // TODO add your handling code here:
        String keyword = t_cari.getText().trim();
        loadData(keyword);
    }//GEN-LAST:event_t_cariKeyReleased

    private void clearForm(Component parent) {
        if (parent instanceof JTextField) {
            ((JTextField) parent).setText("");
        } else if (parent instanceof JComboBox) {
            ((JComboBox<?>) parent).setSelectedIndex(0);
        } else if (parent instanceof JSpinner) {
            ((JSpinner) parent).setValue(0);
        } else if (parent instanceof JCheckBox) {
            ((JCheckBox) parent).setSelected(false);
        } else if (parent instanceof JPanel || parent instanceof Container) {
            for (Component c : ((Container) parent).getComponents()) {
                clearForm(c);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_edit_label;
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_edit;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JButton bt_tambahdata;
    private javax.swing.JPanel data_supplier;
    private javax.swing.JTable datatable;
    private javax.swing.JPanel form_tambah;
    private javax.swing.JTextField input_address;
    private javax.swing.JTextField input_name;
    private javax.swing.JTextField input_phone;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField t_cari;
    private javax.swing.JPanel tambah_supplier;
    // End of variables declaration//GEN-END:variables

}
